spring:
  profiles: 9527
    active: 
---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-atsea-dev
---
spring:
  profiles: test
  application:
    name: microservicecloud-config-atsea-test